//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTraSua.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5GBASI0\\SQLEXPRESS;Database=QuanLyQuanTraSua;Integrated Secur" +
            "ity=True;")]
        public string QuanLyQuanTraSuaConnectionString {
            get {
                return ((string)(this["QuanLyQuanTraSuaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-QKCBFGOJ\\SQLEXPRESS;Initial Catalog=QuanLyQuanTraSua;Integrate" +
            "d Security=True;Encrypt=True;TrustServerCertificate=True")]
        public string QuanLyQuanTraSuaConnectionString1 {
            get {
                return ((string)(this["QuanLyQuanTraSuaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8N51H7P\\SQLEXPRESS;Initial Catalog=QuanLyQuanTraSua;Integrate" +
            "d Security=True;TrustServerCertificate=True")]
        public string QuanLyQuanTraSuaConnectionString2 {
            get {
                return ((string)(this["QuanLyQuanTraSuaConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUANCUONG;Initial Catalog=QuanLyQuanTraSua;Persist Security Info=True" +
            ";User ID=sa;Password=123456")]
        public string QuanLyQuanTraSuaConnectionString3 {
            get {
                return ((string)(this["QuanLyQuanTraSuaConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-QKCBFGOJ\\SQLEXPRESS;Initial Catalog=QuanLyQuanTraSua;Integrate" +
            "d Security=True;TrustServerCertificate=True")]
        public string QuanLyQuanTraSuaConnectionString4 {
            get {
                return ((string)(this["QuanLyQuanTraSuaConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUANCUONG;Initial Catalog=QLYTV;Persist Security Info=True;User ID=sa" +
            ";Password=123456")]
        public string QLYTVConnectionString {
            get {
                return ((string)(this["QLYTVConnectionString"]));
            }
        }
    }
}
